sudo: required
services: 
  - docker

before install:
  - docker build -t craigcliff/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true craigcliff/react-test npm test -- --coverage

after_success:
  - docker build -t craigcliff/multi-client ./client
  - docker build -t craigcliff/multi-nginx ./nginx
  - docker build -t craigcliff/multi-server ./server
  - docker build -t craigcliff/multi-worker ./worker
# Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take images and push to Docker Hub
  - docker push craigcliff/multi-client
  - docker push craigcliff/multi-nginx
  - docker push craigcliff/multi-server
  - docker push craigcliff/multi-worker


deploy:
  provider: elasticbeanstalk
  region: 'eu-west-2'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-eu-west-2-918081770065'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY